name: Deploy typedoc to GitHub Pages

on:
  # Runs when the typescript definitions are updated
  #push:
  #  branches:
  #    - dev
  #  paths:
  #    - 'src/ScriptEditor/NetscriptDefinitions.d.ts'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  mkdocs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy typedoc to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 20
      - run: npm ci
      - run: npx typedoc --out site src/ScriptEditor/NetscriptDefinitions.d.ts
      - uses: actions/upload-pages-artifact@v1
        with:
          name: typedoc
          path: site
      - uses: actions/deploy-pages@v2
        id: deployment
        with:
          artifact_name: typedoc
