# Simple workflow for deploying static content to GitHub Pages
name: Deploy MkDocs to GitHub Pages

on: # Runs on pushes targeting the default branch
  push:
    branches:
      - dev
    paths:
      - 'src/ScriptEditor/NetscriptDefinitions.d.ts'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  mkdocs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy MkDocs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs
      - run: python -m mkdocs build --verbose --clean

      - uses: actions/upload-pages-artifact@v1
        with:
          name: typedoc
          path: site
      - uses: actions/deploy-pages@v2
        id: deployment
        with:
          artifact_name: typedoc
